version: "3"

services:
  redis-cache:
    image: redis:alpine
    restart: always

  redis-queue:
    image: redis:alpine
    restart: always

  redis-socketio:
    image: redis:alpine
    restart: always

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erpnext
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe

  site-creator:
    image: frappe/erpnext-worker:v14
    command: new
    depends_on:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    environment:
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      SITE_NAME: site1.local
      DB_NAME: erpnext
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

  backend:
    image: frappe/erpnext-worker:v14
    restart: always
    depends_on:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

  frontend:
    image: frappe/erpnext-nginx:v14
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

  scheduler:
    image: frappe/erpnext-worker:v14
    restart: always
    command: schedule
    depends_on:
      - backend
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

  worker:
    image: frappe/erpnext-worker:v14
    restart: always
    command: worker
    depends_on:
      - backend
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites

volumes:
  sites-vol: